### ISSUE TITLE
NER任务训练的时候，cEHRNER与cMedQANER两个数据集是如何align实体标签的呢？

### ISSUE THREAD

**Issue by nihuizhidao** [alibaba-research/ChineseBLUE#11]
你好，NER任务训练使用的两个数据集cEHRNER与cMedQANER，使用的标签体系是不一样的，请问这个在数据预处理的时候，是如何映射到统一的标签的呢？

cEHRNER的实体标签为：

`{'疾病和诊断', '影像检查', '实验室检验', '药物', '症状', '手术', '解剖部位'}`

cMedQANER的实体标签为：

`{'physiology', 'test', 'disease', 'time', 'drug', 'symptom', 'body', 'department', 'crowd', 'feature', 'treatment'}`

**Comment by zxlzr** [comment]
您好，我们没有对2个数据集的标签进行统一，此外我们的数据集已经停止维护了，请您移步https://github.com/CBLUEbenchmark/CBLUE
