### ISSUE TITLE
ner 数据集存在大量的标注错误的问题

### ISSUE THREAD

**Issue by hwaking** [alibaba-research/ChineseBLUE#13]
非常感谢提供中文医疗nlp 评测数据集，但是我在观察中发现ner任务中存在很多标注漏了的问题
![image](https://user-images.githubusercontent.com/25998151/126119918-d57a1640-ff6b-4595-aaa4-b6c8f026ce42.png)

**Comment by zxlzr** [comment]
感谢您指出我们数据集存在的问题，这个数据集目前已经停止维护了，麻烦您移步https://github.com/CBLUEbenchmark/CBLUE，我们会提供定期的数据更新。
