### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by Smile-L-up** [alibaba-research/ChineseBLUE#14]
您好，感谢您分享您的工作。我在尝试复现NER任务时，发现F1值在80出头，不知道具体原因。所以想问一下，您这边项目有开源吗？

**Comment by zxlzr** [comment]
你好，F1的问题可能是超参数问题，也可能是您使用了错误的评估方式，ner有好几种评估方式，此外我们这个benchmark已经不再维护啦，请您移步https://github.com/CBLUEbenchmark/CBLUE

**Comment by Smile-L-up** [comment]
> 你好，F1 的问题可能是超参数问题，也可能是您使用了错误的评估方式，有好几种潜在的方式，此外我们这个基准已经不再维护啦，请您移步[https://github .com/CBLUEbenchmark/CBLUE](https://github.com/CBLUEbenchmark/CBLUE)

新连接我之前有看过，这个项目我是搜中文医疗预训练模型搜到的。我查看了一下最新链接的评价指标，指标均采用“macro”，NER没有采用精准匹配（识别位置与类型），不知道论文中所对应的指标是什么？
