### ISSUE TITLE
为什么模型下载之后没有词表

### ISSUE THREAD

**Issue by xunuo2345** [alibaba-research/ChineseBLUE#15]
为什么模型下载之后没有词表

**Comment by zxlzr** [comment]
您好，非常抱歉回复晚了，这个git已经停止维护拉，词表在这里https://github.com/alibaba-research/ChineseBLUE/blob/master/vocab.txt

**Comment by greatheart1000** [comment]
好的😊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月28日 19:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [alibaba-research/ChineseBLUE] 为什么模型下载之后没有词表 (Issue #15) |

您好，非常抱歉回复晚了，这个git已经停止维护拉，词表在这里https://github.com/alibaba-research/ChineseBLUE/blob/master/vocab.txt
