### ISSUE TITLE
有huggingface仓库么，你这个pretrain没法用啊，没有词表不说，也只有tf版本的

### ISSUE THREAD

**Issue by iris-qq** [alibaba-research/ChineseBLUE#16]

**Comment by zxlzr** [comment]
您好，非常抱歉回复晚了，这个git已经停止维护啦，词表在这里https://github.com/alibaba-research/ChineseBLUE/blob/master/vocab.txt ， 我们暂时没提供huggingface，这个项目也已经close好些年了。
