### ISSUE TITLE
有关于MC-BERT的咨询

### ISSUE THREAD

**Issue by yyxx1997** [alibaba-research/ChineseBLUE#17]

**Comment by yyxx1997** [comment]
我对您的一作论文《Conceptualized Representation Learning for Chinese Biomedical Text Mining》很感兴趣，但也有些细节比较疑惑，还望您不吝赐教。
在文中，您多次提到利用知识图谱抽取中文医药实体，这个知识图谱或者知识库是指的什么，并且是否公开呢？另外，文中提到的“CognitiveConceptGraph”现在已经访问不了，请问这是怎么回事呢？
希望得到您的回复，万分感谢！

**Comment by zxlzr** [comment]
您好感谢关注，

1. 是知识图谱，这是内部知识图谱不会公开，您可以使用一些公开知识图谱如CPubMed-KG https://cpubmed.openi.org.cn/graph/wiki#
2. CognitiveConceptGraph 中的部分数据在这里发布了https://github.com/alibaba-research/ConceptGraph 有一个demo http://openconcepts.openkg.cn/, 这里数据不是面向医疗的，完整数据也不会发布非常抱歉
3. 您也可以关注我们最新维护的https://github.com/CBLUEbenchmark/CBLUE (医疗数据) 和 https://tianchi.aliyun.com/dataset/122271?lang=zh-cn 数字商务知识图谱

**Comment by yyxx1997** [comment]
十分感谢您的回复！
