### ISSUE TITLE
感谢！请问能发布下 字典 和 预训练的相关超参数吗？

### ISSUE THREAD

**Issue by wulaoshi** [alibaba-research/ChineseBLUE#5]
我想在此基础上接着预训练，请问能发布下 字典 和 预训练 相关超参数吗？

**Comment by zxlzr** [comment]
字典是内部数据无法发布抱歉，超参数参见谷歌官方的，batchsize 根据卡的显存情况调整就可以

**Comment by wulaoshi** [comment]
> 字典是内部数据无法发布抱歉，超参数参见谷歌官方的，batchsize 根据卡的显存情况调整就可以

您好，是这样的：发布版本是 tensorflow，我们转成 pytorch 后，没有字典，就没法用。。。请问能发布下字典吗？

**Comment by zxlzr** [comment]
这个词典和原始中文的词典是一样的, 21128行
