### ISSUE TITLE
请问预训练模型，mc_bert是在医疗预料集训练过吗

### ISSUE THREAD

**Issue by Williamlizl** [alibaba-research/ChineseBLUE#6]
试了一下，与其他模型结果chinese_wwm_ext_pytorch完全一样，请问是vocab.txt的问题吗

**Comment by zxlzr** [comment]
vocab是一致的，放出的模型只在医疗小规模语料训练了1轮，结果具有随机性，是可能结果区别不大的，后续有计划放持续训练的模型。
