### ISSUE TITLE
您好，请问可以说明一下ChineseBLUE收集的数据集来自哪些学术评测任务吗？

### ISSUE THREAD

**Issue by trueto** [alibaba-research/ChineseBLUE#8]
如题，观察您收集的数据集有来自CCKS的，也有来自CHIP的。
不太清楚cMedIC来自哪个评测任务。

**Comment by zxlzr** [comment]
数据集来自ccks2019、ccks2020的医疗ner评测比赛，另外我们数据集已经不再维护啦，请您移步https://github.com/CBLUEbenchmark/CBLUE
