### ISSUE TITLE
关于cMedQA数据集标注问题

### ISSUE THREAD

**Issue by sunyilgdx** [alibaba-research/ChineseBLUE#9]
您好，很感谢您开源的数据集和模型，但是我在下载查看cMedQA数据集时，发现标注的Label大多是不正确的，请问是否数据集存储出现了问题？

**Comment by squareRoot3** [comment]
+1, 感觉无论标签是0还是1, Q和A都没有任何关系

**Comment by hwaking** [comment]
> 您好，很感谢您开源的数据集和模型，但是我在下载查看cMedQA数据集时，发现标注的Label大多是不正确的，请问是否数据集存储出现了问题？

我在查看ner标注数据时，同样发现此类问题

**Comment by zxlzr** [comment]
您好，我们的数据集已经不再维护啦，对数据集中出现的错误深表歉意，请您移步https://github.com/CBLUEbenchmark/CBLUE

**Comment by zhangsheng93** [comment]
关于cMedQA，我检查了一下和原始作者发布版本有区别，建议您使用原始cMedQA v1.0 和cMedQA v2.0 

[cMedQA v1.0](https://github.com/zhangsheng93/cMedQA)  
[cMedQA v2.0](https://github.com/zhangsheng93/cMedQA2) 

> 您好，很感谢您开源的数据集和模型，但是我在下载查看cMedQA数据集时，发现标注的Label大多是不正确的，请问是否数据集存储出现了问题？
